version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/project
    restart: unless-stopped

  db:
    image: postgres:13.3-alpine
    env_file:
      - .env
    volumes:
      - posgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  posgres_data: { }
