# Generated by Django 4.0.3 on 2022-03-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MusicalWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("contributors", models.TextField()),
                (
                    "iswc",
                    models.CharField(blank=True, max_length=16, null=True, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MusicalWorkMetaDataFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="")),
                ("is_processed", models.BooleanField(default=False)),
            ],
        ),
    ]
